import type { Client, Project } from "@/lib/types";

/**
 * Contenido de muestra. Solo se usa cuando Supabase todavía no está
 * configurado, para poder ver y ajustar el diseño antes de conectar el canal.
 * En cuanto existen las variables de entorno, esto deja de renderizarse.
 * Los nombres de cliente son ficticios.
 */

function cover(seed: string, w = 1600, h = 900) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

const base = {
  youtubeId: null,
  source: "manual" as const,
  status: "published" as const,
  hidden: false,
  credits: [],
  gallery: [],
  extraVideos: [],
  makingOf: [],
  socialLinkedin: null,
  socialInstagram: null,
  socialFacebook: null,
  results: null,
};

export const demoProjects: Project[] = [
  {
    ...base,
    id: "demo-1",
    slug: "aldabra-ron-anejo-siete",
    title: "Aldabra Ron, Añejo Siete",
    projectName: "Añejo Siete",
    clientName: "Aldabra Ron",
    clientSlug: "aldabra-ron",
    year: 2025,
    projectDate: "2025-09-18",
    services: ["Dirección", "Dirección de fotografía", "Color", "Post producción"],
    category: "Publicidad",
    location: "Salta",
    story:
      "Siete años de barrica contados en cuarenta segundos. Filmamos en la bodega durante dos noches, con luz práctica y cámara en mano, para que la pieza tuviera la textura del lugar y no la de un set.",
    tags: ["publicidad", "bebidas", "salta"],
    coverUrl: cover("om-aldabra", 1920, 1080),
    featured: true,
    sortOrder: 1,
    durationSeconds: 42,
    publishedAt: "2025-09-18T12:00:00Z",
    aiSummary:
      "Campaña de lanzamiento para el añejo de siete años de Aldabra, filmada en bodega con luz práctica.",
    seoTitle: "Añejo Siete para Aldabra Ron | ONNIS & MEEKS",
    seoDescription:
      "Campaña de lanzamiento filmada en Salta. Dirección, fotografía, color y post producción.",
    keywords: ["publicidad", "bebidas", "salta", "campaña"],
    homeExcerpt: "Siete años de barrica contados en cuarenta segundos",
  },
  {
    ...base,
    id: "demo-2",
    slug: "kioto-bike-co-serie-urbana",
    title: "Kioto Bike Co., Serie Urbana",
    projectName: "Serie Urbana",
    clientName: "Kioto Bike Co.",
    clientSlug: "kioto-bike-co",
    year: 2025,
    projectDate: "2025-06-04",
    services: ["Producción ejecutiva", "Aéreas y drone", "Post producción"],
    category: "Branded content",
    location: "Buenos Aires",
    story:
      "Tres ciclistas, un domingo a las seis de la mañana y una ciudad vacía. El plan de rodaje se armó alrededor de la luz, no al revés.",
    tags: ["branded content", "deporte", "ciudad"],
    coverUrl: cover("om-kioto", 1920, 1080),
    featured: true,
    sortOrder: 2,
    durationSeconds: 96,
    publishedAt: "2025-06-04T12:00:00Z",
    aiSummary:
      "Serie de tres piezas para el lanzamiento de la línea urbana de Kioto Bike Co.",
    seoTitle: "Serie Urbana para Kioto Bike Co. | ONNIS & MEEKS",
    seoDescription:
      "Tres piezas filmadas en Buenos Aires al amanecer. Producción, aéreas y post.",
    keywords: ["branded content", "deporte", "buenos aires"],
    homeExcerpt: "Una ciudad vacía a las seis de la mañana",
  },
  {
    ...base,
    id: "demo-3",
    slug: "fundacion-ribera-el-agua-vuelve",
    title: "Fundación Ribera, El agua vuelve",
    projectName: "El agua vuelve",
    clientName: "Fundación Ribera",
    clientSlug: "fundacion-ribera",
    year: 2024,
    projectDate: "2024-11-22",
    services: ["Dirección", "Sonido y música", "Color"],
    category: "Documental de marca",
    location: "Entre Ríos",
    story:
      "Un corto de doce minutos sobre la recuperación de un humedal. Cinco jornadas de rodaje repartidas en un año, para poder mostrar el cambio real del paisaje.",
    tags: ["documental", "ambiente", "entre ríos"],
    coverUrl: cover("om-ribera", 1920, 1080),
    featured: true,
    sortOrder: 3,
    durationSeconds: 726,
    publishedAt: "2024-11-22T12:00:00Z",
    aiSummary:
      "Documental de doce minutos sobre la recuperación de un humedal en Entre Ríos.",
    seoTitle: "El agua vuelve para Fundación Ribera | ONNIS & MEEKS",
    seoDescription:
      "Documental de marca filmado durante un año en Entre Ríos. Dirección, sonido y color.",
    keywords: ["documental", "ambiente", "humedal"],
    homeExcerpt: "Un año de rodaje para mostrar cómo vuelve un humedal",
  },
  {
    ...base,
    id: "demo-4",
    slug: "motta-deportes-temporada-cero",
    title: "Motta Deportes, Temporada Cero",
    projectName: "Temporada Cero",
    clientName: "Motta Deportes",
    clientSlug: "motta-deportes",
    year: 2024,
    projectDate: "2024-03-09",
    services: ["Dirección", "Post producción", "Fotografía de campaña"],
    category: "Publicidad",
    location: "Córdoba",
    story:
      "Rodaje de dos días que salió en video, gráfica y redes. Una sola dirección de arte para toda la campaña.",
    tags: ["publicidad", "deporte", "retail"],
    coverUrl: cover("om-motta", 1920, 1080),
    featured: false,
    sortOrder: 4,
    durationSeconds: 61,
    publishedAt: "2024-03-09T12:00:00Z",
    aiSummary:
      "Campaña integral de temporada para Motta Deportes, con video y gráfica del mismo rodaje.",
    seoTitle: "Temporada Cero para Motta Deportes | ONNIS & MEEKS",
    seoDescription: "Campaña de temporada filmada en Córdoba. Video, gráfica y redes.",
    keywords: ["publicidad", "deporte", "córdoba"],
    homeExcerpt: "Dos días de rodaje para video, gráfica y redes",
  },
  {
    ...base,
    id: "demo-5",
    slug: "terrazas-del-sur-cosecha-nocturna",
    title: "Terrazas del Sur, Cosecha Nocturna",
    projectName: "Cosecha Nocturna",
    clientName: "Terrazas del Sur",
    clientSlug: "terrazas-del-sur",
    year: 2023,
    projectDate: "2023-04-15",
    services: ["Dirección de fotografía", "Aéreas y drone", "Color"],
    category: "Institucional",
    location: "Mendoza",
    story:
      "La cosecha se hace de noche para cuidar la uva. Filmamos con la misma lógica: sensores altos, poca luz agregada y todo el trabajo resuelto en cámara.",
    tags: ["institucional", "vino", "mendoza"],
    coverUrl: cover("om-terrazas", 1920, 1080),
    featured: false,
    sortOrder: 5,
    durationSeconds: 148,
    publishedAt: "2023-04-15T12:00:00Z",
    aiSummary:
      "Pieza institucional sobre la cosecha nocturna en Mendoza, filmada casi sin luz agregada.",
    seoTitle: "Cosecha Nocturna para Terrazas del Sur | ONNIS & MEEKS",
    seoDescription:
      "Institucional filmado de noche en Mendoza. Fotografía, aéreas y color.",
    keywords: ["institucional", "vino", "mendoza"],
    homeExcerpt: "La cosecha se hace de noche y filmamos igual",
  },
  {
    ...base,
    id: "demo-6",
    slug: "estudio-bonpland-piezas-de-taller",
    title: "Estudio Bonpland, Piezas de taller",
    projectName: "Piezas de taller",
    clientName: "Estudio Bonpland",
    clientSlug: "estudio-bonpland",
    year: 2023,
    projectDate: "2023-08-30",
    services: ["Dirección", "Post producción", "Sonido y música"],
    category: "Contenido para redes",
    location: "Buenos Aires",
    story:
      "Doce piezas cortas para publicar durante seis meses, filmadas en una sola jornada en el taller.",
    tags: ["redes", "diseño", "serie"],
    coverUrl: cover("om-bonpland", 1920, 1080),
    featured: false,
    sortOrder: 6,
    durationSeconds: 38,
    publishedAt: "2023-08-30T12:00:00Z",
    aiSummary:
      "Serie de doce piezas cortas para redes, resueltas en una sola jornada de rodaje.",
    seoTitle: "Piezas de taller para Estudio Bonpland | ONNIS & MEEKS",
    seoDescription: "Serie de doce piezas cortas para redes filmadas en una jornada.",
    keywords: ["redes", "serie", "diseño"],
    homeExcerpt: "Doce piezas para seis meses, en una sola jornada",
  },
];

export const demoClients: Client[] = [
  {
    id: "dc-1",
    slug: "aldabra-ron",
    name: "Aldabra Ron",
    logoUrl: null,
    logoSlug: null,
    story: "Destilería de Salta. Trabajamos el lanzamiento de su línea añejada.",
    website: null,
    services: ["Dirección", "Color", "Post producción"],
    sortOrder: 1,
  },
  {
    id: "dc-2",
    slug: "kioto-bike-co",
    name: "Kioto Bike Co.",
    logoUrl: null,
    logoSlug: null,
    story: "Fabricante de bicicletas urbanas. Tres temporadas de contenido.",
    website: null,
    services: ["Producción ejecutiva", "Aéreas y drone"],
    sortOrder: 2,
  },
  {
    id: "dc-3",
    slug: "fundacion-ribera",
    name: "Fundación Ribera",
    logoUrl: null,
    logoSlug: null,
    story: "Organización ambiental. Un documental filmado durante un año.",
    website: null,
    services: ["Dirección", "Sonido y música"],
    sortOrder: 3,
  },
  {
    id: "dc-4",
    slug: "motta-deportes",
    name: "Motta Deportes",
    logoUrl: null,
    logoSlug: null,
    story: "Cadena de retail deportivo. Campaña de temporada integral.",
    website: null,
    services: ["Dirección", "Fotografía de campaña"],
    sortOrder: 4,
  },
  {
    id: "dc-5",
    slug: "terrazas-del-sur",
    name: "Terrazas del Sur",
    logoUrl: null,
    logoSlug: null,
    story: "Bodega mendocina. Institucional de cosecha.",
    website: null,
    services: ["Dirección de fotografía", "Color"],
    sortOrder: 5,
  },
  {
    id: "dc-6",
    slug: "estudio-bonpland",
    name: "Estudio Bonpland",
    logoUrl: null,
    logoSlug: null,
    story: "Estudio de diseño de objetos. Serie de contenido para redes.",
    website: null,
    services: ["Dirección", "Post producción"],
    sortOrder: 6,
  },
];
